"""Reader-facing transparency labels (planning.md §5). Text is fixed per variant, copied verbatim from the spec."""

LABEL_VARIANTS = {
    "high_confidence_ai": {
        "headline": "Likely AI-generated",
        "body": ("Our automated checks found strong signs that this piece was mostly or entirely generated by an AI "
                 "tool. Automated checks can be wrong, and the creator can appeal this label."),
    },
    "uncertain": {
        "headline": "Origin unclear",
        "body": ("Our automated checks couldn't tell with confidence whether a person or an AI tool wrote this "
                 "piece. This note is here to give you context. It is not an accusation."),
    },
    "high_confidence_human": {
        "headline": "Likely human-written",
        "body": ("Our automated checks found the patterns we usually see in a person's own writing, and no strong "
                 "signs of AI generation."),
    },
    "under_review": {
        "headline": "Label under review",
        "body": ("The creator has asked for this piece's label to be reviewed by a person. Until that review is "
                 "done, treat the earlier automated result with caution."),
    },
    "verified_human": {
        "headline": "Verified human: creator shared their drafts",
        "body": ("The creator completed an extra verification step by sharing an earlier draft that shows how this "
                 "piece was revised over time. Certificate {certificate_id}, issued {date}."),
    },
}

ATTRIBUTION_TO_VARIANT = {
    "likely_ai": "high_confidence_ai",
    "uncertain": "uncertain",
    "likely_human": "high_confidence_human",
}


def confidence_text(confidence):
    """Confidence in words, never a decimal (§5)."""
    if confidence is None:
        return "Our confidence: low"
    if confidence >= 0.90:
        return "Our confidence: high"
    if confidence >= 0.75:
        return "Our confidence: moderate"
    return "Our confidence: low"


def label_variant_for(attribution, status="classified", certificate=None):
    """Precedence: verified certificate > open appeal > reviewer overturn > automated attribution."""
    if certificate:
        return "verified_human"
    if status == "under_review":
        return "under_review"
    if status == "resolved_overturned":
        return "high_confidence_human"
    return ATTRIBUTION_TO_VARIANT.get(attribution, "uncertain")


def build_label(attribution, confidence, status="classified", certificate=None):
    variant = label_variant_for(attribution, status, certificate)
    spec = LABEL_VARIANTS[variant]
    body = spec["body"]
    if variant == "verified_human":
        issued = str(certificate.get("issued_at") or "")[:10]  # YYYY-MM-DD
        body = body.format(certificate_id=certificate.get("certificate_id", ""), date=issued)
    return {
        "variant": variant,
        "headline": spec["headline"],
        "body": body,
        "confidence_text": confidence_text(confidence),
    }
