"""Signal 1 — LLM judge via Groq (planning.md §3 Signal 1; image variant §9.4).

Never raises: any failure returns {"available": False, "details": {"error": ...}}.
"""

import json
import os
import re

from dotenv import load_dotenv

load_dotenv()

NAME = "llm"
MODELS = ["openai/gpt-oss-120b", "openai/gpt-oss-20b"]
TIMEOUT_S = 20
MAX_TOKENS = 1024
MAX_INPUT_CHARS = 6000

TEXT_SYSTEM_PROMPT = (
    "You are a careful forensic linguist who estimates whether a piece of writing was generated by an AI "
    "language model or written by a person. Look for: generic 'assistant voice', hedged and balanced framing, "
    "stock transitions, absence of lived specifics, and over-smooth structure (AI); versus personal specifics, "
    "idiosyncratic voice, informal or uneven phrasing, and genuine opinion (human). Formal or non-native English "
    "alone is NOT evidence of AI; academic prose written by people is common. Use the full 0-100 range and be "
    "calibrated: reserve values above 85 or below 15 for clear cases.\n"
    'Reply with ONLY a JSON object: {"ai_likelihood": <integer 0-100>, "reasoning": "<one sentence>"}'
)

IMAGE_SYSTEM_PROMPT = (
    "You estimate whether an image was AI-generated, using only its file metadata and the creator's "
    "description/caption (you cannot see the pixels). AI generator software names, prompt/seed/sampler fields, "
    "and descriptions that read like generation prompts suggest AI; camera make/model, exposure settings, GPS "
    "and descriptions of a real shoot suggest a photograph or human-made work. Missing metadata is weak "
    "evidence either way. Be calibrated and use the full 0-100 range.\n"
    'Reply with ONLY a JSON object: {"ai_likelihood": <integer 0-100>, "reasoning": "<one sentence>"}'
)

_client = None
_client_error = None


def _get_client():
    global _client, _client_error
    if _client is not None:
        return _client
    key = os.getenv("GROQ_API_KEY")
    if not key:
        _client_error = "GROQ_API_KEY not set"
        return None
    try:
        from groq import Groq
        _client = Groq(api_key=key, timeout=TIMEOUT_S, max_retries=0)
        _client_error = None
    except Exception as exc:  # pragma: no cover - depends on environment
        _client_error = f"client init failed: {exc}"
        _client = None
    return _client


def llm_available():
    """True if an API key is configured and the Groq client can be constructed (no network call)."""
    return _get_client() is not None


def extract_json(content):
    """Parse {"ai_likelihood", "reasoning"} from model output; tolerant of code fences and surrounding prose."""
    if not content:
        return None
    content = content.strip()
    try:
        obj = json.loads(content)
        if isinstance(obj, dict):
            return obj
    except ValueError:
        pass
    for m in re.finditer(r"\{[^{}]*\}", content, re.DOTALL):
        try:
            obj = json.loads(m.group(0))
            if isinstance(obj, dict) and "ai_likelihood" in obj:
                return obj
        except ValueError:
            continue
    m = re.search(r'"?ai_likelihood"?\s*[:=]\s*(\d+(?:\.\d+)?)', content)
    if m:
        r = re.search(r'"?reasoning"?\s*[:=]\s*"([^"]*)"', content)
        return {"ai_likelihood": float(m.group(1)), "reasoning": r.group(1) if r else ""}
    return None


def _call(client, model, system, user, use_json_mode):
    kwargs = dict(
        model=model,
        messages=[{"role": "system", "content": system}, {"role": "user", "content": user}],
        temperature=0,
        max_tokens=MAX_TOKENS,
    )
    if use_json_mode:
        kwargs["response_format"] = {"type": "json_object"}
    resp = client.chat.completions.create(**kwargs)
    return resp.choices[0].message.content or ""


def _judge(system, user):
    client = _get_client()
    if client is None:
        return {"name": NAME, "score": None, "available": False, "details": {"error": _client_error}}

    errors = []
    for model in MODELS:
        for use_json_mode in (True, False):
            try:
                content = _call(client, model, system, user, use_json_mode)
            except Exception as exc:
                errors.append(f"{model} (json_mode={use_json_mode}): {type(exc).__name__}: {str(exc)[:200]}")
                # Only a 400 (e.g. JSON mode rejected / json_validate_failed) is worth retrying without JSON mode;
                # timeouts, auth and connection errors move straight on to the next model.
                if getattr(exc, "status_code", None) == 400:
                    continue
                break
            obj = extract_json(content)
            if obj is None:
                errors.append(f"{model} (json_mode={use_json_mode}): unparseable/empty content {content[:120]!r}")
                continue
            try:
                value = float(obj["ai_likelihood"])
            except (KeyError, TypeError, ValueError):
                errors.append(f"{model}: missing/invalid ai_likelihood in {obj!r}"[:200])
                continue
            score = max(0.0, min(1.0, value / 100.0))
            return {
                "name": NAME,
                "score": round(score, 3),
                "available": True,
                "details": {
                    "reasoning": str(obj.get("reasoning", ""))[:500],
                    "raw_ai_likelihood": value,
                    "model": model,
                    "json_mode": use_json_mode,
                    **({"earlier_errors": errors} if errors else {}),
                },
            }
    return {"name": NAME, "score": None, "available": False, "details": {"error": "; ".join(errors)[:1000]}}


def llm_signal(text):
    text = (text or "")[:MAX_INPUT_CHARS]
    if not text.strip():
        return {"name": NAME, "score": None, "available": False, "details": {"error": "empty text"}}
    user = f"Text to evaluate:\n<<<\n{text}\n>>>"
    return _judge(TEXT_SYSTEM_PROMPT, user)


def llm_image_signal(metadata, description=None):
    meta_json = json.dumps(metadata or {}, default=str, ensure_ascii=False)[:3000]
    desc = (description or "").strip()[:2000] or "(none provided)"
    user = f"Image metadata (JSON):\n{meta_json}\n\nCreator's description/caption:\n{desc}"
    return _judge(IMAGE_SYSTEM_PROMPT, user)
